### ISSUE TITLE
Backpack items lost in update

### ISSUE THREAD

**Issue by ChopTV** [kwpugh/simple_backpack#49]
I'm in the process of testing updating our server from 1.18 to 1.19 and one of the first things we noticed was that all of the backpacks are empty. Is there a way to preserve their contents? Or a way to return their contents?

**Comment by kwpugh** [comment]
That is unfortunate.  I do not support updating mods from one minecraft version to the next.  The backpack was about 70% rewritten, so it is not surprising.

There would have been to way to transfer or preserve the contents.

It is generally recommended to start a fresh world when upgrading modpack from one minecraft version to another.

**Comment by dranorter** [comment]
@ChopTV Sorry I didn't keep an eye on bugs here but I'd like to inform you, over a year late, that I encountered this issue as well and eventually solved it. See issue #45 . I had to write a program to search through my entire worldfile and change the NBT data capitalization appropriately. The root cause seems to have been a change in the Fabric API.
